### ISSUE TITLE
Almost there!

### ISSUE THREAD

**Issue by toddheslin** [jonasacres/siteomatic#1]
This is a super-cooper readme and I'm almost done but I've got one issue.

After making the settings.cgf and sites.cfg I'm running:
```
bin/siteomatic settings.cfg sites.cgf
```
and I'm receiving the error:
```
~/siteomatic$ bin/siteomatic settings.cfg sites.cfg
Loading config settings.cfg
/var/lib/gems/1.9.1/gems/parseconfig-1.0.6/lib/parseconfig.rb:45:in `validate_config': Permission denied - settings.cfg is not readable (Errno::EACCES)
```
I'm guessing it's file permissions. Any ideas?

**Comment by jonasacres** [comment]
I guess I'll get the obvious question out of the way -- are you sure the settings.cfg is in fact readable by your user?

**Comment by toddheslin** [comment]
Well, my guess is yes but I still get these things wrong. See attached image:
![screenshot 2015-04-28 07 15 39](https://cloud.githubusercontent.com/assets/1883112/7358072/83a191cc-ed76-11e4-8e9b-9e2c45359f65.png)

**Comment by jonasacres** [comment]
It looks like you're writing ".cfg" when invoking siteomatic, but your actual filenames are ".cgf". :) Might try renaming the files.

**Comment by toddheslin** [comment]
Oh...dear...me.

Thanks @jonasacres! I've got it up and running now. Will continue testing it out.
